### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by Mrkomiljon** [NationalGAILab/HoT#4]
How to solve this problem?

**Comment by chopin1998** [comment]
❯ python demo/vis.py --video ~/datasets/aaa.mp4

Generating 2D pose...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/marco/Build/pose/HoT/demo/vis.py", line 334, in <module>
    get_pose2D(video_path, output_dir)
  File "/home/marco/Build/pose/HoT/demo/vis.py", line 105, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "/home/marco/Build/pose/HoT/demo/lib/hrnet/gen_kpts.py", line 164, in gen_video_kpts
    keypoints = keypoints.transpose(1, 0, 2, 3)  # (T, M, N, 2) --> (M, T, N, 2)
ValueError: axes don't match array


same problem....
